import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;

/**
 * It represents a log where the application events are stored.
 * 
 * @author  Roberto Castillejo Embid.
 * @version 1.0.
 */
public class Logger 
{
	private File file;		//The file where the events are saved.
	
	/**
	 * Default constructor for Logger.
	 */
	public Logger()
	{
		file = new File("Queens_Log.log");
	}
	
	/**
	 * Logger constructor that takes a file as a parameter.
	 * 
	 * @param newFile	A file.
	 */
	public Logger(File newFile)
	{
		file = newFile;
	}
	
	/**
	 * Returns a File object.
	 * 
	 * @return	A File object.
	 */
	public File getArchivo()
	{
		return file;
	}
	
	/**
	 * Replace a File object with a new one passed as a parameter.
	 * 
	 * @param newFile		A File object.
	 */
	public void setArchivo(File newFile)
	{
		file = newFile;
	}
	
	/**
	 * Save the events generated by the application with the day, date and time they occur.
	 * 
	 * @param text		A file name.
	 */
	public void writeInLog(String text)
	{
		FileWriter out = null;
		PrintWriter pw = null;
		try{
			out = new FileWriter(file, true);
			pw = new PrintWriter(out);
			String date = insertDate(); //Save the event date.
						
			if(file.length() == 0){		//It's time to create the log
				pw.println("                                    APPLICATION LOG " + "\"" + "QUEENS" + "\"");
				pw.println();
				pw.println("                      ==============================================================");
				pw.println("                      * Author:      Roberto Castillejo Embid.                     *");
				pw.println("                      * Version:     1.0.                                          *");
				pw.println("                      ==============================================================");
				pw.println();
			}
			
			pw.print(date + "     ");
			pw.println(text);
		}
		catch(Exception e){
			System.out.println("Error: There was a problem with the log file: Queens_Log.log");
		}
		finally{
			try{
			//Ensure the file is closed.
				if(out != null){
					out.close();
				}
			}
			catch(Exception e){
				System.out.println("Error: There was a problem with the log file: Queens_Log.log");
			}
		}
	}
	
	
	/**
	 * Returns the current date in the specified format. An example 
	 * of the format would be: "Mon Dec 12 2016 22:17:43"
	 * 
	 * @return		The current date in a specific format.
	 */
	private String insertDate()
	{
		Date date = new Date();
		String currentDate = date.insertDate();
		
		return currentDate;	
	}
}
